# Generated by Django 3.0.3 on 2020-03-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_num', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=100)),
                ('book_author_fname', models.CharField(max_length=50)),
                ('book_author_lname', models.CharField(max_length=100)),
            ],
        ),
    ]
