# Generated by Django 3.0.3 on 2020-03-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_num', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=100)),
                ('book_author_fname', models.CharField(blank=True, max_length=50)),
                ('book_author_lname', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
