# Generated by Django 2.0.7 on 2020-04-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Improvements',
            field=models.TextField(blank=True),
        ),
    ]
