# Generated by Django 3.0.3 on 2020-04-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_feedback_improvements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='userName',
            new_name='Name',
        ),
    ]
